"""Add payment table

Revision ID: 135dafe820b7
Revises: 
Create Date: 2020-07-19 22:34:04.222789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '135dafe820b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variable_symbol', sa.String(length=10), nullable=True),
    sa.Column('note', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variable_symbol')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    # ### end Alembic commands ###
